### ISSUE TITLE
Tag Parser time out

### ISSUE THREAD

**Issue by DNx5** [DenizenScript/Depenizen#210]
When using Depenizen extension tags inside world script events, it never get filled and resulting in server crash when its too long waiting.
example:
```yaml
TestScript:
  type: world
  events:
    on test command:
    - narrate <player.is_afk>
    - determine fulfilled
```
Environment:
Server: ``Paper version git-Paper-1452 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)``
Denizen: ``version: 1.0.2-SNAPSHOT (build 383), core version: 1.15 (Build 148)``
Depenizen: ``version: 1.0.0 (build 408)``
