### ISSUE TITLE
GeyserMC & Floodgate support

### ISSUE THREAD

**Issue by spikehidden** [DenizenScript/Depenizen#381]
I'm surprised that no one suggested this earlier as there is a huge potential what you can do with Geyser & Floodgate.
Especially the forms that you can show Bedrock Players which are easier to use than chest UIs especially for console players.

Geyser Wiki for Floodgate API: https://wiki.geysermc.org/floodgate/api/

Down are a few ideas of what could be implemented.

## Tags

- **<playerTag.geyser.is_bedrock>** - _returns if the player joined via Geyser_
- **<playerTag.floodgate.version>** - _gets the clients version_
- **<playerTag.floodgate.device>** - _returns the player's device (Java, Win10, iOS, android, Xbox, ect.)_
- **<playerTag.floodgate.locale>** - _returns which language the player has set_
- **<playerTag.floodgate.xuid>** - _gets the players XUID_
- **<playerTag.floodgate.is_linked>** - _returns if the Bedrock Player has a linked Java Account_
- **<playerTag.floodgate.linktype>** - _returns if the Account is globally or locally linked_
- **<playerTag.floodgate.whitelist>** - _returns the floodgate player whitelist as list_
- **<playerTag.floodgate.username>** - _returns the Xbox live playertag of the player_

## Events

- **geyser player pushes <button> in <form>** - _For button pushes in simple and modal "[forms](https://wiki.geysermc.org/floodgate/forms/)"_

> - **<context.type>** - _returns the form type_
> - **<context.button>** - _returns the position of the pushed button_
> - **<context.button_name>** - _returns the text of the pushed button_
> - **<context.form>** - _returns the form script ID_

- **geyser player submits <customForm>** - _For submits of custom "[forms](https://wiki.geysermc.org/floodgate/forms/)"_

> - **<context.type>** - _returns the form type_
> - **<context.data>** - _returns the submited data as a map tag_
> - **<context.form>** - _returns the form script ID_

### New Player Event Switches
isGeyserPlayer:[true/false]
device:[Java/Win10/iOS/android/Xbox/...]

## Commands

- **cumulus [open/close] (for:\<playerTag\>|\<playerTag\>|...) (form:\<formID\>)** - _to open a form for the Bedrock player_

#### Modal Forms
```yaml
CumulusScript:
  type: cumulus
  formType: modal
  fields:
    title: title
    content: content
    buttons:
      1: Button1
      2: Button2
```
#### Simple forms
```yaml
CumulusScript:
  type: cumulus
  formType: simple
  fields:
    title: title
    buttons:
      1:
        texture: textures/i/glyph_world_template.png
        text: Button with texture image
      2: 
        url: https://github.com/GeyserMC.png?size=200
        text: Button with URL image
      2:
        text: Button without an image
```
#### Custom forms
```yaml
CumulusScript:
  type: cumulus
  formType: simple
  fields:
    title: title
    buttons:
      1:
        type: dropdown
        title: title
        options: option1|option2|...
      2: 
        type: input
        title: title
        placeholder: placeholder
      3:
        type: toggle
        title: title
      4:
        type: slider
        title: title
        slider: 0|1|5|10|the|cake|is|a|lie
```
